spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://ep-floral-union-a1c28c4q-pooler.ap-southeast-1.aws.neon.tech/booken?sslmode=require
    username: neondb_owner
    password: npg_cU0GzNkOID7E
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    placeholders:
      flyway.postgresql.allow.unsupported: true
